
---
- name: Converge
  hosts: all

  tasks:
    - name: Update yum cahce on Centos.
      ansible.builtin.yum:
        update_cache: true
    - name:
      ansible.builtin.yum: 
        name: selinux-policy
        state: present
    - name:
      ansible.builtin.yum: 
        name: openssh-server
        state: present
    - name:
      ansible.builtin.yum: 
        name: openssh-clients
        state: present

- import_playbook: ../../main.yml
