---
- name: Converge
  hosts: all

  tasks:
    - name: Update yum cahce on Centos.
      ansible.builtin.yum:
        update_cache: true
    - name: Ensure selinux-policy is present
      ansible.builtin.yum:
        name: selinux-policy
        state: present
    - name: Ensure openssh-server is present
      ansible.builtin.yum:
        name: openssh-server
        state: present
    - name: Ensure openssh-clients is present
      ansible.builtin.yum:
        name: openssh-clients
        state: present
    - name: Ensure sshd is running.
      service:
        name: sshd
        state: started

- import_playbook: ../../main.yml
