---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Ensure user is present"
    user:
      name: mghalbi
      state: present
    register: new_user
  - name: "check if user exists"
    assert:
      that:
        - new_user.user == "mghalbi"
      success_msg: "user exist"
      fail_msg: "user dosent exist"
